version: '3'
services:
  jekyll:
    image: 'starefossen/github-pages'
    ports:
      - "4000:4000"
    volumes:
      - ".:/usr/src/app"
    command: "jekyll serve -s ./jekyll -d ./dist --watch -H 0.0.0.0 -P 4000"

