# Site settings
name: SARD JV Limited
title: SARD JV Limited
email: info@sardjv.co.uk
description: "Appraisal and revalidation management software for doctors and nurses. A joint venture between Oxleas NHS Foundation Trust and Mango Swiss Limited."
baseurl: ""
url: "http://www.sardjv.co.uk"

excerpt_separator: <!-- more -->

# Build settings
markdown: kramdown
permalinks: pretty

include:
  - '.htaccess'
  - '_*.scss'
  - '_pdfs'
