medical_revalidation:
  name_image: products/medrv_inline.png
  current_product: true
  image400x: products/medrv_icon.png
  product_page: products/medical_revalidation.html
  description: |
    <p>SARD Medical Revalidation covers all aspects of the appraisal and
    revalidation process to full GMC requirements, including evidence portfolio
    creation, online MAG form, Educator’s Appraisal functionality and powerful
    real-time reporting capabilities. Simple to use and highly configurable
    to meet your organisation’s unique requirements, with built-in live chat
    support for doctors.</p>
    <h3>Features</h3>
    <ul>
    <li>Configurable Evidence Portfolio</li>
    <li>Secure 24/7/365 web access from anywhere</li>
    <li>Powerful custom compliance reporting</li>
    <li>Advanced administration and user management system</li>
    <li>Advanced search and real-time reporting functionality</li>
    <li>Individual, Appraiser and Responsible Officer dashboards</li>
    <li>Import MAG forms automatically for quick start</li>
    <li>Educator’s Appraisal module</li>
    <li>Complete audit trail</li>
    <li>Fully configurable automatic reminder system</li>
    </ul>
    <h3>Advantages</h3>
    <ul>
    <li>Access all medical revalidation information via a single,
    powerful interface</li>
    <li>Simple and intuitive, immediate increase in user engagement</li>
    <li>System access from multiple devices</li>
    <li>Major administrative savings over existing data capture methods</li>
    <li>Flexible to the unique requirements of each organisation</li>
    <li>Familiar MAG form-style interface to 'ease in' new users</li>
    <li>Designed by an NHS trust and software specialists</li>
    <li>Improve compliance and engagement rates via powerful
    reporting features</li>
    <li>Best-in-class doctor and technical support via live chat</li>
    </ul>

360:
  name_image: products/360_inline.png
  current_product: true
  image400x: products/360_icon.png
  product_page: products/360.html
  description: |
    <p>SARD 360 is a simple, easy to use multi-source feedback module
    designed to work hand in hand with other SARD products. Based on
    the GMC patient, colleague and self-assessment questionnaires, it is
    built with the necessary flexibility to reflect the differing requirements
    of individual roles within NHS trusts.</p>
    <h3>Features</h3>
    <ul>
    <li>Full self-assessment, patient and colleague feedback system</li>
    <li>Advanced real-time reporting functionality</li>
    <li>Results checked against national benchmarking data</li>
    <li>Accurately reflects differing 360 requirements</li>
    <li>Built around standard GMC questionnaires</li>
    <li>Instantly email forms to users and non-users</li>
    <li>Rapid data entry of paper forms</li>
    <li>Complete audit trail</li>
    <li>Advanced administration and user management system</li>
    <li>Secure 24/7/365 web access from anywhere</li>
    </ul>
    <h3>Advantages</h3>
    <ul>
    <li>Simple and intuitive - immediate increase in user engagement</li>
    <li>Improve compliance and engagement rates via comprehensive
    reporting features</li>
    <li>System access from multiple devices</li>
    <li>Progress tracking against set requirements</li>
    <li>Ability to reflect difficult roles within trusts</li>
    <li>Familiarity through custom branding</li>
    <li>Designed with a major NHS trust alongside software specialists</li>
    <li>Best-in-class doctor and technical support</li>
    <li>Quick, simple to use and user-driven, administration-light approach</li>
    <li>Access all 360 information via a single interface</li>

jobplanning:
  name_image: products/jobplanning_inline.png
  current_product: true
  image400x: products/jobplanning_icon.png
  product_page: products/jobplanning.html
  description: |
    <p>SARD Job Planning is an intuitive, powerful, simple to use calendar-based
    system designed to ensure rapid data entry, accurate job plans and data
    ready for capacity planning and rostering. Built to reflect the reality of
    medical work and to capture all schedules, however complex. Full custom
    sign-off and reporting.</p>
    <h3>Features</h3>
    <ul>
    <li>Rapid, straightforward data entry for all types of activity</li>
    <li>A true iCal calendar system to allow full, detailed reporting</li>
    <li>Instant automatic calculations of all hours and PAs</li>
    <li>Secure 24/7/365 web access from anywhere</li>
    <li>Best-in-class doctor and technical support via live chat</l>
    <li>Custom activity types, categories, locations</li>
    <li>Custom mandatory sign-offs to meet organisational needs</li>
    <li>Instant heat-map overview of full job plan</li>
    <li>Import from existing calendars</li>
    <li>Full audit trail</li>
    </ul>
    <h3>Advantages</h3>
    <li>Simple and intuitive. Immediately increase user engagement</li>
    <li>Rapid, easy data entry of all types of work</li>
    <li>Major administrative savings over existing data capture methods</li>
    <li>Access all job planning information via a single powerful interface</li>
    <li>Accurately and completely reflect users' working schedules</li>
    <li>System access from multiple devices</li>
    <li>Provides accurate information for capacity planning</li>
    <li>Designed in collaboration with major NHS trusts</li>
    <li>Easily handle the most complex job plans</li>
    <li>Flexible to the unique requirements of each organisation</li>
    </ul>

eleave:
  name_image: products/eleave_inline.png
  current_product: true
  image400x: products/eleave_icon.png
  product_page: products/eleave.html
  description: |
    <p>SARD eLeave is a simple, easy to use leave tracking and authorising
    solution designed to fit seamlessly with other SARD products now and
    in the future. An elegantly intuitive way to submit and manage leave
    requests and to support accurate capacity planning.</p>
    <h3>Features</h3>
    <ul>
    <li>Annual leave allowance tracker/calculation</li>
    <li>Request annual leave/study leave</li>
    <li>Covers any leave type including paternity/maternity, sick and
    compassionate leave</li>
    <li>Request/report/log custom leave</li>
    <li>Full auditing capability</li>
    <li>Simple and elegant - fully colour coded, user friendly calendar</li>
    <li>Manager acceptance/rejection of requests</li>
    <li>Manager overview of leave booked</li>
    <li>Email notifications</li>
    <li>Highlight leave overlap/clashes</li>
    <li>Full reporting capability of leave taken</li>
    </ul>
    <h3>Advantages</h3>
    <ul>
    <li>Ability to interact with SARD Job Planning</li>
    <li>Save time - easy data entry and overview of leave requests</li>
    <li>Simple, intuitive design promotes user engagement</li>
    <li>Limit support requests</li>
    <li>Access all leave information via a single powerful interface</li>
    <li>Flexible to unique trust requirements</li>
    <li>Accurately reflects users' leave</li>
    <li>Accessible from multiple browsers</li>
    <li>Plan leave based on availability to ensure coverage</li>
    <li>Developed in collaboration with major NHS trust, so it solves the problems you      have</li>
    <li>Unrivalled SARD customer service support via live chat, telephone and email</li>
    </ul>

nurse_revalidation:
  name_image: products/nurserv_inline.png
  current_product: true
  image400x: products/nurserv_icon.png
  product_page: products/nurse_revalidation.html
  description: |
    <p>The SARD Nurse and Midwife Revalidation system is purpose-built to
    meet all requirements set out by the NMC, incorporating Practice Hours,
    CPD, Practice Related Feedback, Reflection and Discussion, Health
    and Character, Professional Indemnity Arrangements and Third Party
    Confirmation. Designed for nurses and administrators who value speed,
    simplicity, auditing and compliance.</p>
    <h3>Features</h3>
    <ul>
    <li>Fast and intuitive interface built on the latest User Interface technology</li>
    <li>Access all nurse revalidation data via a single dashboard</li>
    <li>Powerful custom compliance reporting</li>
    <li>Secure 24/7/365 web access from anywhere</li>
    <li>Advanced search and real-time reporting functionality</li>
    <li>Advanced administration and user management system</li>
    <li>Complete audit trail</li>
    <li>Intuitive structured workflow for user and confirmer</li>
    <li>Highly configurable and flexible to your unique requirements</li>
    <li>CSV user importation</li>
    </ul>
    <h3>Advantages</h3>
    <ul>
    <li>Quick and simple to use, user-driven, administration-light approach</li>
    <li>Clear and intuitive. Immediately increase user engagement</li>
    <li>Improve compliance and engagement rates via powerful,
    straightforward reporting features</li>
    <li>Rapid and easy implementation</li>
    <li>System access from multiple devices</li>
    <li>Major administrative savings over traditional data capture methods</li>
    <li>System branding reflecting your organisation</li>
    <li>Designed by software experts in collaboration with NHS trusts</li>
    <li>Best-in-class SARD user and technical support</li>
    <li>Advanced permissions system to allow full access control
    and customisation</li>
    </ul>


appraisal_for_all:
  name_image: products/appforall_inline.png
  current_product: true
  image400x: products/appforall_icon.png
  product_page: products/appraisal_for_all.html
  description: |
    <p>SARD Appraisal for All is designed to meet the appraisal needs of all staff,
    within the healthcare sector and beyond. Our system covers all aspects of
    the process, including appraisal questions, objectives, ratings and CPD.
    Its powerful core flexibility means it can reflect your unique appraisal and
    compliance requirements.</p>
    <h3>Features</h3>
    <ul>
    <li>Fast, simple, intuitive interface built on the latest User
    Interface technology</li>
    <li>Highly configurable to reflect existing appraisal forms and processes</li>
    <li>Advanced search and real-time reporting functionality</li>
    <li>Comprehensive administration and user management system</li>
    <li>Secure 24/7/365 web access from anywhere</li>
    <li>Individual dashboards to plot progression</li>
    <li>Fully configurable guidance to reflect organisational requirements</li>
    <li>CSV user importation</li>
    <li>Custom policies and policy reports</li>
    <li>Complete audit trail</li>
    </ul>
    <h3>Advantages</h3>
    <ul>
    <li>Access all appraisal information via a single interface</li>
    <li>Simple and intuitive - see an immediate increase in user engagement</li>
    <li>Improve compliance and engagement rates via comprehensive
    reporting features</li>
    <li>Major administrative savings over existing data capture methods</li>
    <li>Centralised and uniform appraisal process</li>
    <li>Powerful custom compliance reporting at your fingertips</li>
    <li>Links to revalidation requirements</li>
    <li>Best-in-class user and technical support</li>
    <li>System access from multiple devices</li>
    <li>Designed by appraisal and software specialists</li>
    </ul>

